Fix Operation in Wrong Order error for Krylov approximation
msmdev/pyGPCCA pull request #42
Opened 2022-10-14 14:00 UTC by dburkhardt

It seems there's an incompatibility with the current version of SLEPC when using a Krylov approximation for getting the sorted schur decomposition.

See recommendation from the SLEPC devs here:
https://gitlab.com/slepc/slepc4py/-/issues/41

Fixing this function removes the error message.

2022-10-14 14:13 UTC, msmdev commented
@michalk8, could you please take a look on this please, since you are more into the SLEPc dependencies topic, esp. with respect to MacOS etc.?

2022-10-14 14:15 UTC, msmdev commented
@dburkhardt, could you please provide info regarding the OS and versions of SLEPc, CellRank and pyGPCCA you are using?

2022-10-14 15:09 UTC, dburkhardt commented
I'm using Debian GNU/Linux 11 (bullseye) and SLEPC version 3.18 and pyGPCCA version 1.0.3.

CellRank isn't needed to reproduce the issue. It sounds like this is just a new requirement from SLEPC version 3.18 which was released on 2022-10-01. https://gitlab.com/slepc/slepc/-/blob/main/CHANGELOG.md#318-2022-10-01

2022-10-19 11:22 UTC, michalk8 requested changes
Thanks @dburkhardt ! Could you please modify the following files and fix the linting please?
- https://github.com/msmdev/pyGPCCA/blob/main/setup.py#L39-L42
- https://github.com/msmdev/pyGPCCA/blob/main/.github/workflows/ci.yml#L65-L67

2022-10-19 13:21 UTC, msmdev commented on pygpcca/__init__.py
> +__version__ = "1.0.4"
@dburkhardt, please don't bump the pyGPCCA version. I will do this separately after adding some other changes.

2022-10-19 13:21 UTC, msmdev commented on setup.py
> +    __version__ = "1.0.4"
@dburkhardt, no bumping please.

2022-10-19 13:21 UTC, dburkhardt commented
@michalk8 , I edited the request files. I assume you're okay with pinning to the most recent version of SLEPC/PETSC? It seems there is always going to be an incompatibility with versions <3.18 and versions ≥3.18.

2022-10-19 13:22 UTC, msmdev requested changes
Please don't bump pyGPCCA version.

2022-10-19 13:28 UTC, msmdev commented
@dburkhardt @michalk8 `ubuntu-latest, 3.8, true` still fails with
```
./.scripts/ci/install_dependencies.sh: line 8: pushd: petsc-3.18: No such file or directory
Error: Process completed with exit code 1.
```

2022-10-19 13:29 UTC, msmdev commented
@dburkhardt, linting still fails. You should use the `pre-commit` hook to solve this issue.

2022-10-19 13:32 UTC, michalk8 commented on .github/workflows/ci.yml
> +            PC_VERSION: 3.18  # PETSc version
This should also include the minor version as `3.18.0`, that's the reason why the CI script fails.

2022-10-19 14:47 UTC, dburkhardt commented
I see got it! I think I've made the requested edits correctly. Thanks for the help.

2022-10-19 15:29 UTC, msmdev commented
> I see got it! I think I've made the requested edits correctly. Thanks for the help.

@dburkhardt, all tests pass, thus I will merge the PR.
Thank you very much for bringing the issue up and solving it!

2022-10-19 15:30 UTC, msmdev approved these changes

2022-10-19 15:31 UTC, msmdev commented
@michalk8, do you approve? If so, please approve the changes to allow the merge, thx!

2022-10-19 17:04 UTC, michalk8 approved these changes

2022-10-19 17:05 UTC, michalk8 commented
LGTM, thanks @dburkhardt !

2022-10-19 17:05 UTC, merged